Repository red-hat-storage/common-ci-utils, pull requests merged in 2023-10, with the labels that each got.

#1 Commonly used function needed for NooBaa Standalone deployment
  .gitignore
  common/__init__.py
  common/command_runner.py
  common/exceptions.py
  common/file_system_utils.py
  common/host_info.py
  common/package_fetcher.py
  common/postgres_utils.py
  common/rpm_manager.py
  common/templating.py
  requirements.txt
  setup.py
Labels: size/L

#2 Update common repository structure
  README.md
  common_ci_utils/__init__.py
  common_ci_utils/command_runner.py
  common_ci_utils/config/default.yaml
  common_ci_utils/config/noobaa-sa/default.yaml
  common_ci_utils/exceptions.py
  common_ci_utils/file_system_utils.py
  common_ci_utils/host_info.py
  common_ci_utils/package_fetcher.py
  common_ci_utils/postgres_utils.py
  common_ci_utils/rpm_manager.py
  common_ci_utils/templating.py
  setup.py
Labels: size/M

#3 fix import paths
  common_ci_utils/file_system_utils.py
  common_ci_utils/postgres_utils.py
  common_ci_utils/rpm_manager.py
Labels: size/S

#4 Pypi requirements
  CHANGELOG.md
  LICENSE
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/L
